[project]
name = "medicalscribe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.8",
    "faster-whisper>=1.2.1",
    "uvicorn>=0.40.0",
]
